name: Backend CI

on:
  push:
    branches: [master, ci-cd-github-actions]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (ci with fallback)
        run: |
          if [ -f package-lock.json ]; then
            echo "package-lock.json found; trying npm ci";
            if npm ci; then
              echo "npm ci succeeded";
            else
              echo "npm ci failed; falling back to npm install";
              npm install;
            fi
          else
            echo "No package-lock.json; running npm install";
            npm install;
          fi

      - name: Lint filenames
        run: npm run check:filenames

      - name: Run tests
        run: npm test
        env:
          MONGODB_URI_TEST: mongodb://127.0.0.1:27017/smart-business-ai-test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/test-results/
          if-no-files-found: ignore

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-business-ai-backend:latest
