name: Backend CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Install & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies (clean)
        run: npm ci

      - name: Filename convention check
        run: npm run check:filenames

      - name: Run test suite
        env:
          MONGODB_URI_TEST: mongodb://127.0.0.1:27017/smart-business-ai-test
          NODE_ENV: test
        run: npm test

  docker:
    name: Docker Build & Push (master only)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN && 'true' || 'false' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-business-ai-backend:latest

      - name: Image digest
        run: echo "Image built and (if authenticated) pushed." 