name: Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      component:
        description: "Component to deploy"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - backend
          - admin-dashboard
          - user-dashboard
      environment:
        description: "Deployment environment"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

env:
  NODE_VERSION: "18.x"

jobs:
  deploy-backend-prod:
    name: Deploy Backend to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.component == 'all' || github.event.inputs.component == 'backend' || github.event_name == 'release'
    environment:
      name: production-backend
      url: https://api.yourdomain.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Backend
        run: npm run build --workspace=packages/backend

      - name: Run Database Migrations
        run: |
          echo "Running database migrations..."
          # npm run migration:run --workspace=packages/backend

      - name: Deploy Backend
        run: |
          echo "🚀 Deploying backend to production..."
          echo "Backend API: https://api.yourdomain.com"
          # Add production deployment commands here

      - name: Health Check
        run: |
          echo "Performing health check..."
          # curl -f https://api.yourdomain.com/health || exit 1

  deploy-admin-prod:
    name: Deploy Admin Dashboard to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.component == 'all' || github.event.inputs.component == 'admin-dashboard' || github.event_name == 'release'
    environment:
      name: production-admin
      url: https://admin.yourdomain.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Admin Dashboard
        run: npm run build --workspace=packages/admin-dashboard
        env:
          NEXT_PUBLIC_API_URL: https://api.yourdomain.com
          NEXT_PUBLIC_ENV: production

      - name: Deploy Admin Dashboard
        run: |
          echo "🚀 Deploying admin dashboard to production..."
          echo "Admin Dashboard: https://admin.yourdomain.com"
          # Add production deployment commands here

      - name: Verify Deployment
        run: |
          echo "Verifying admin dashboard deployment..."
          # Add verification steps

  deploy-user-prod:
    name: Deploy User Dashboard to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.component == 'all' || github.event.inputs.component == 'user-dashboard' || github.event_name == 'release'
    environment:
      name: production-user
      url: https://app.yourdomain.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Build User Dashboard
        run: npm run build --workspace=packages/user-dashboard
        env:
          NEXT_PUBLIC_API_URL: https://api.yourdomain.com
          NEXT_PUBLIC_ENV: production

      - name: Deploy User Dashboard
        run: |
          echo "🚀 Deploying user dashboard to production..."
          echo "User Dashboard: https://app.yourdomain.com"
          # Add production deployment commands here

      - name: Verify Deployment
        run: |
          echo "Verifying user dashboard deployment..."
          # Add verification steps

  rollback:
    name: Rollback if Needed
    runs-on: ubuntu-latest
    needs: [deploy-backend-prod, deploy-admin-prod, deploy-user-prod]
    if: failure()
    steps:
      - name: Rollback Deployment
        run: |
          echo "🔄 Rolling back failed deployment..."
          echo "Component failures detected, initiating rollback procedures"
          # Add rollback commands here

  post-deployment:
    name: Post-Deployment Tasks
    runs-on: ubuntu-latest
    needs: [deploy-backend-prod, deploy-admin-prod, deploy-user-prod]
    if: success()
    steps:
      - name: Clear Cache
        run: |
          echo "🧹 Clearing application caches..."
          # Add cache clearing commands

      - name: Warm Up Applications
        run: |
          echo "🔥 Warming up applications..."
          # curl https://api.yourdomain.com/health
          # curl https://admin.yourdomain.com
          # curl https://app.yourdomain.com

      - name: Send Success Notification
        run: |
          echo "✅ Production deployment completed successfully!"
          echo "Backend: https://api.yourdomain.com"
          echo "Admin: https://admin.yourdomain.com"
          echo "App: https://app.yourdomain.com"
