name: Enforce staging -> production PRs only

on:
  pull_request_target:
    branches: [production]

jobs:
  gatekeeper:
    name: Verify PR comes from staging
    runs-on: ubuntu-latest
    steps:
      - name: Ensure source branch is staging
        run: |
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"
          if [ "$GITHUB_HEAD_REF" != "staging" ]; then
            echo "Only PRs from 'staging' may be merged into 'production'. Please open a PR into 'staging' first." >&2
            exit 1
          fi
